language: node_js

node_js:
  - node

notifications:
  slack: nautilus27:KINyb2Dz1Q0BhTOOauVIlTIU

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build
  - yarn test
  - python3 -VV
  - pip -V

before_deploy:
  - "echo 'Deploying to nautilusdev.com s3 bucket'"
  # install aws cli
  - python3 -m pip install --user awscli
  # Append exe location to our PATH
  - export PATH=$PATH:$HOME/.local/bin

env:
  global: PATH=/opt/python/3.7.1/bin:$PATH

deploy:
  provider: script
  skip_cleanup: true
  on: master
  script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh

branches:
  only:
    - master
